spring:
  application:
    name: ContasTeste

  datasource:
    url: jdbc:postgresql://postgres:5432/contas
    username: contas
    password: contas
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  file:
    path: logs

